site_name: 'RAG Pattern Knowledge Base'
site_description: 'A repository to consolidate knowledge articles, patterns, white papers, relevant articles supporting RAG pattern.'
site_author: 'Ankur Kumar'
docs_dir: 'docs'
site_dir: 'html'
theme:
  name: 'material'
  palette:
    primary: indigo
  features:
    - navigation.instant
    - search.highlight

nav:
  - Home: 'index.md'
  - Reference Architecture: 'ReferenceArchitecture/README.md'
  - Vector Databases: 'VectorDatabases/README.md'
  - Design Patterns: 'DesignPatterns/README.md'
  # Add more pages here

plugins:
  - search
  - mermaid2